use release_management;

INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv10_ac1', 'build_job', 'Build Job', 'sv10');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv10_ac2', 'create_job', 'Create Job', 'sv10');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv10_ac3', 'clone_job', 'Clone Job', 'sv10');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv11_ac1', 'create_issue', 'Create Issue', 'sv11');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv11_ac2', 'get_projects', 'Get Projects', 'sv11');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv11_ac3', 'get_issues', 'Get Issues', 'sv11');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv12_ac1', 'load_test', 'Load Test', 'sv12');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv13_ac1', 'create_cluster', 'Create Cluster', 'sv13');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv13_ac2', 'deploy_application', 'Deploy Application', 'sv13');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv14_ac1', 'run_command', 'Run Command', 'sv14');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv14_ac2', 'run_script', 'Run Script', 'sv14');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv15_ac1', 'build_artifactory', 'Build Artifactory', 'sv15');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv16_ac1', 'create_tables', 'Create Tables', 'sv16');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv17_ac1', 'run_query', 'Run Query', 'sv17');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv18_ac1', 'build_war', 'Build War', 'sv18');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv19_ac1', 'run_query', 'Run Query', 'sv19');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv19_ac2', 'create_database', 'Create Database', 'sv19');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv19_ac3', 'delete_database', 'Delete Database', 'sv19');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv19_ac4', 'run_playbook_host', 'Run Playbook Host', 'sv19');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv1_ac1', 'project_data', 'Project Data', 'sv1');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv1_ac2', 'project_info', 'Project Info', 'sv1');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv20_ac1', 'manual', 'Manual', 'sv20');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv21_ac1', 'create_tables', 'Create Tables', 'sv21');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv22_ac1', 'get', 'Get', 'sv22');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv22_ac2', 'post', 'Post', 'sv22');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv23_ac1', 'create_incident', 'Create Incident', 'sv23');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv23_ac2', 'update_incident', 'Update Incident', 'sv23');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv24_ac1', 'get_rules', 'Get Rules', 'sv24');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv24_ac2', 'get_metrics', 'Get Metrics', 'sv24');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv25_ac1', 'run_job', 'Run Job', 'sv25');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv25_ac2', 'generate_report', 'Generate Report', 'sv25');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv26_ac1', 'commit_files', 'Commit Files', 'sv26');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv27_ac1', 'run_terraform', 'Run Terraform', 'sv27');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv28_ac1', 'deploy_application', 'Deploy Application', 'sv28');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv29_ac1', 'deploy_application', 'Deploy Application', 'sv29');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv29_ac2', 'deploy_datasource', 'Deploy Datasource', 'sv29');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv29_ac3', 'jms_queue', 'Jms Queue', 'sv29');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv2_ac1', 'run_playbook_host', 'Run Playbook Host', 'sv2');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv2_ac2', 'run_playbook_hostfile', 'Run Playbook Hostfile', 'sv2');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv30_ac1', 'create_roles', 'Create Roles', 'sv30');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv31_ac1', 'create_ami', 'Create Ami', 'sv31');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv32_ac1', 'create_infra', 'Create Infra', 'sv32');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv33_ac1', 'Build_job', 'Build Job', 'sv33');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv3_ac1', 'clone_plan', 'Clone Plan', 'sv3');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv3_ac10', 'delete_plan', 'Delete Plan', 'sv3');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv3_ac11', 'continue_build', 'Continue Build', 'sv3');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv3_ac12', 'get_build_queue', 'Get Build Queue', 'sv3');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv3_ac13', 'get_results', 'Get Results', 'sv3');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv3_ac14', 'get_branch_results', 'Get Branch Results', 'sv3');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv3_ac15', 'get_projects', 'Get Projects', 'sv3');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv3_ac16', 'pause', 'Pause', 'sv3');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv3_ac17', 'resume', 'Resume', 'sv3');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv3_ac2', 'enable_plan', 'Enable Plan', 'sv3');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv3_ac3', 'queue_build', 'Queue Build', 'sv3');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv3_ac4', 'get_builds_by_label', 'Get Builds By Label', 'sv3');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv3_ac5', 'get_builds', 'Get Builds', 'sv3');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv3_ac6', 'get_deployments', 'Get Deployments', 'sv3');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv3_ac7', 'get_environment_results', 'Get Environment Results', 'sv3');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv3_ac8', 'get_plans', 'Get Plans', 'sv3');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv3_ac9', 'get_branches', 'Get Branches', 'sv3');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv4_ac1', 'create_repository', 'Create Repository', 'sv4');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv4_ac2', 'listall_repository', 'Listall Repository', 'sv4');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv4_ac3', 'access_repository', 'Access Repository', 'sv4');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv4_ac4', 'update_repository', 'Update Repository', 'sv4');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv4_ac5', 'delete_repository', 'Delete Repository', 'sv4');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv4_ac6', 'archieve_repository', 'Archieve Repository', 'sv4');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv4_ac7', 'get_branches', 'Get Branches', 'sv4');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv4_ac8', 'get_tags', 'Get Tags', 'sv4');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv5_ac1', 'run_cft', 'Run Cft', 'sv5');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv6_ac1', 'project_data', 'Project Data', 'sv6');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv7_ac1', 'build_job', 'Build Job', 'sv7');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv7_ac2', 'pull_job', 'Pull Job', 'sv7');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv7_ac3', 'push_job', 'Push Job', 'sv7');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv8_ac1', 'push_repo', 'Push Repo', 'sv8');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv8_ac2', 'clone_repo', 'Clone Repo', 'sv8');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv8_ac3', 'create_repo', 'Create Repo', 'sv8');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv8_ac4', 'pull_repo', 'Pull Repo', 'sv8');
INSERT INTO actions (action_id, name, description, service_id) VALUES ('sv9_ac1', 'deploy_application', 'Deploy Application', 'sv9');

commit;