INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (1, 'AIX');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (2, 'AV / Security Definitions Servers');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (3, 'BYOD Servers (Citrix)');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (4, 'Enterprise / Domains');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (5, 'KMS (Licensing)');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (6, 'LDAP - desktop (Active Directory)');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (7, 'LDAP - MidTier (eDirectory)');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (8, 'Linux');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (9, 'Storage / SAN');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (10, 'Telephony (Servers)');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (11, 'Video Conference  / Communications Servers');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (12, 'Windows');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (13, 'Totals');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (14, 'Apache');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (15, 'APIGateway');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (16, 'Mqueue (Mainframe & Mid-tier)');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (17, 'JVM');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (18, 'Misc');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (19, 'Introscope (WAS, MULE, & TC)');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (20, 'WebMethods');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (21, 'WebSphere');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (22, 'Datacom');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (23, 'DB/2 LUW');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (24, 'DB/2 zOS');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (25, 'IMS');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (26, 'Mongo');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (27, 'MySQL');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (28, 'Oracle');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (29, 'SQL Server');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (30, 'ACF2');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (31, 'Mainframe - IPO1');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (32, 'Mainframe - SYSA');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (33, 'RACF');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (34, 'Zeke / Zena');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (35, 'Firewall');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (36, 'Oracle Identity Manager');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (37, 'Core Network (F5, Routers, Switches)');
INSERT INTO release_management.infra_metrics_subcomponent (subcomponent_id, subcomponent_name) VALUES (38, 'Web Access Manager (Oracle & Novell)');